CREATE TABLE `encounter` (
  `id`                 INT(11)    NOT NULL AUTO_INCREMENT,
  `encounter_id`       INT(11)    NOT NULL,
  `encounter_type`     INT(11)    NOT NULL,
  `patient_id`         INT(11)    NOT NULL DEFAULT '0',
  `location_id`        INT(11)             DEFAULT NULL,
  `form_id`            INT(11)             DEFAULT NULL,
  `encounter_datetime` DATETIME   NOT NULL,
  `creator`            INT(11)    NOT NULL DEFAULT '0',
  `date_created`       DATETIME   NOT NULL,
  `voided`             TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`          INT(11)             DEFAULT NULL,
  `date_voided`        DATETIME            DEFAULT NULL,
  `void_reason`        VARCHAR(255)        DEFAULT NULL,
  `changed_by`         INT(11)             DEFAULT NULL,
  `date_changed`       DATETIME            DEFAULT NULL,
  `visit_id`           INT(11)             DEFAULT NULL,
  `uuid`               CHAR(38)   NOT NULL,
  `facility`           CHAR(38),
  `state`              CHAR(12),
  PRIMARY KEY (`id`),
  KEY `encounter_datetime_idx` (`encounter_datetime`),
  KEY `encounter_ibfk_1` (`creator`),
  KEY `encounter_type_id` (`encounter_type`),
  KEY `encounter_form` (`form_id`),
  KEY `encounter_location` (`location_id`),
  KEY `encounter_patient` (`patient_id`),
  KEY `user_who_voided_encounter` (`voided_by`),
  KEY `encounter_changed_by` (`changed_by`),
  KEY `encounter_visit_id_fk` (`visit_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `obs` (
  `id`                  INT(11)    NOT NULL AUTO_INCREMENT,
  `obs_id`              INT(11)    NOT NULL,
  `person_id`           INT(11)    NOT NULL,
  `concept_id`          INT(11)    NOT NULL DEFAULT '0',
  `encounter_id`        INT(11)             DEFAULT NULL,
  `order_id`            INT(11)             DEFAULT NULL,
  `obs_datetime`        DATETIME   NOT NULL,
  `location_id`         INT(11)             DEFAULT NULL,
  `obs_group_id`        INT(11)             DEFAULT NULL,
  `accession_number`    VARCHAR(255)        DEFAULT NULL,
  `value_group_id`      INT(11)             DEFAULT NULL,
  `value_boolean`       TINYINT(1)          DEFAULT NULL,
  `value_coded`         INT(11)             DEFAULT NULL,
  `value_coded_name_id` INT(11)             DEFAULT NULL,
  `value_drug`          INT(11)             DEFAULT NULL,
  `value_datetime`      DATETIME            DEFAULT NULL,
  `value_numeric`       DOUBLE              DEFAULT NULL,
  `value_modifier`      VARCHAR(2)          DEFAULT NULL,
  `value_text`          TEXT,
  `value_complex`       VARCHAR(255)        DEFAULT NULL,
  `comments`            VARCHAR(255)        DEFAULT NULL,
  `creator`             INT(11)    NOT NULL DEFAULT '0',
  `date_created`        DATETIME   NOT NULL,
  `voided`              TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`           INT(11)             DEFAULT NULL,
  `date_voided`         DATETIME            DEFAULT NULL,
  `void_reason`         VARCHAR(255)        DEFAULT NULL,
  `uuid`                CHAR(38)   NOT NULL,
  `facility`            CHAR(38),
  `state`               CHAR(12),
  `previous_version`    INT(11)             DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `obs_datetime_idx` (`obs_datetime`),
  KEY `obs_concept` (`concept_id`),
  KEY `obs_enterer` (`creator`),
  KEY `encounter_observations` (`encounter_id`),
  KEY `obs_location` (`location_id`),
  KEY `obs_grouping_id` (`obs_group_id`),
  KEY `obs_order` (`order_id`),
  KEY `person_obs` (`person_id`),
  KEY `answer_concept` (`value_coded`),
  KEY `obs_name_of_coded_value` (`value_coded_name_id`),
  KEY `answer_concept_drug` (`value_drug`),
  KEY `user_who_voided_obs` (`voided_by`),
  KEY `previous_version` (`previous_version`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE `patient` (
  `patient_id`     INT(11)     NOT NULL,
  `creator`        INT(11)     NOT NULL DEFAULT '0',
  `date_created`   DATETIME    NOT NULL,
  `changed_by`     INT(11)              DEFAULT NULL,
  `date_changed`   DATETIME             DEFAULT NULL,
  `voided`         TINYINT(1)  NOT NULL DEFAULT '0',
  `voided_by`      INT(11)              DEFAULT NULL,
  `date_voided`    DATETIME             DEFAULT NULL,
  `void_reason`    VARCHAR(255)         DEFAULT NULL,
  `allergy_status` VARCHAR(50) NOT NULL DEFAULT 'Unknown',
  `facility`       CHAR(38),
  `state`          CHAR(12),
  PRIMARY KEY (`patient_id`),
  KEY `user_who_changed_pat` (`changed_by`),
  KEY `user_who_created_patient` (`creator`),
  KEY `user_who_voided_patient` (`voided_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE `patient_identifier` (
  `id`                    INT(11)     NOT NULL AUTO_INCREMENT,
  `patient_identifier_id` INT(11)     NOT NULL,
  `patient_id`            INT(11)     NOT NULL DEFAULT '0',
  `identifier`            VARCHAR(50) NOT NULL DEFAULT '',
  `identifier_type`       INT(11)     NOT NULL DEFAULT '0',
  `preferred`             TINYINT(1)  NOT NULL DEFAULT '0',
  `location_id`           INT(11)              DEFAULT '0',
  `creator`               INT(11)     NOT NULL DEFAULT '0',
  `date_created`          DATETIME    NOT NULL,
  `date_changed`          DATETIME             DEFAULT NULL,
  `changed_by`            INT(11)              DEFAULT NULL,
  `voided`                TINYINT(1)  NOT NULL DEFAULT '0',
  `voided_by`             INT(11)              DEFAULT NULL,
  `date_voided`           DATETIME             DEFAULT NULL,
  `void_reason`           VARCHAR(255)         DEFAULT NULL,
  `uuid`                  CHAR(38)    NOT NULL,
  `facility`              CHAR(38),
  `state`                 CHAR(12),
  PRIMARY KEY (`id`),
  KEY `identifier_name` (`identifier`),
  KEY `idx_patient_identifier_patient` (`patient_id`),
  KEY `identifier_creator` (`creator`),
  KEY `defines_identifier_type` (`identifier_type`),
  KEY `patient_identifier_ibfk_2` (`location_id`),
  KEY `identifier_voider` (`voided_by`),
  KEY `patient_identifier_changed_by` (`changed_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE `patient_program` (
  `id`                 INT(11)    NOT NULL AUTO_INCREMENT,
  `patient_program_id` INT(11)    NOT NULL,
  `patient_id`         INT(11)    NOT NULL DEFAULT '0',
  `program_id`         INT(11)    NOT NULL DEFAULT '0',
  `date_enrolled`      DATETIME            DEFAULT NULL,
  `date_completed`     DATETIME            DEFAULT NULL,
  `location_id`        INT(11)             DEFAULT NULL,
  `outcome_concept_id` INT(11)             DEFAULT NULL,
  `creator`            INT(11)    NOT NULL DEFAULT '0',
  `date_created`       DATETIME   NOT NULL,
  `changed_by`         INT(11)             DEFAULT NULL,
  `date_changed`       DATETIME            DEFAULT NULL,
  `voided`             TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`          INT(11)             DEFAULT NULL,
  `date_voided`        DATETIME            DEFAULT NULL,
  `void_reason`        VARCHAR(255)        DEFAULT NULL,
  `uuid`               CHAR(38)   NOT NULL,
  `facility`           CHAR(38),
  `state`              CHAR(12),
  PRIMARY KEY (`id`),
  KEY `user_who_changed` (`changed_by`),
  KEY `patient_program_creator` (`creator`),
  KEY `patient_in_program` (`patient_id`),
  KEY `program_for_patient` (`program_id`),
  KEY `user_who_voided_patient_program` (`voided_by`),
  KEY `patient_program_location_id` (`location_id`),
  KEY `patient_program_outcome_concept_id_fk` (`outcome_concept_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE `patient_state` (
  `id`                 INT(11)    NOT NULL AUTO_INCREMENT,
  `patient_state_id`   INT(11)    NOT NULL,
  `patient_program_id` INT(11)    NOT NULL DEFAULT '0',
  `start_date`         DATE                DEFAULT NULL,
  `end_date`           DATE                DEFAULT NULL,
  `creator`            INT(11)    NOT NULL DEFAULT '0',
  `date_created`       DATETIME   NOT NULL,
  `changed_by`         INT(11)             DEFAULT NULL,
  `date_changed`       DATETIME            DEFAULT NULL,
  `voided`             TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`          INT(11)             DEFAULT NULL,
  `date_voided`        DATETIME            DEFAULT NULL,
  `void_reason`        VARCHAR(255)        DEFAULT NULL,
  `uuid`               CHAR(38)   NOT NULL,
  `facility`           CHAR(38),
  `state`              CHAR(12),
  PRIMARY KEY (`id`),
  KEY `patient_state_changer` (`changed_by`),
  KEY `patient_state_creator` (`creator`),
  KEY `patient_program_for_state` (`patient_program_id`),
  KEY `state_for_patient` (`state`),
  KEY `patient_state_voider` (`voided_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `person` (
  `id`                  INT(11)    NOT NULL AUTO_INCREMENT,
  `person_id`           INT(11)    NOT NULL,
  `gender`              VARCHAR(50)         DEFAULT '',
  `birthdate`           DATE                DEFAULT NULL,
  `birthdate_estimated` TINYINT(1) NOT NULL DEFAULT '0',
  `dead`                TINYINT(1) NOT NULL DEFAULT '0',
  `death_date`          DATETIME            DEFAULT NULL,
  `cause_of_death`      INT(11)             DEFAULT NULL,
  `creator`             INT(11)             DEFAULT NULL,
  `date_created`        DATETIME   NOT NULL,
  `changed_by`          INT(11)             DEFAULT NULL,
  `date_changed`        DATETIME            DEFAULT NULL,
  `voided`              TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`           INT(11)             DEFAULT NULL,
  `date_voided`         DATETIME            DEFAULT NULL,
  `void_reason`         VARCHAR(255)        DEFAULT NULL,
  `uuid`                CHAR(38)   NOT NULL,
  `facility`            CHAR(38),
  `state`               CHAR(12),
  `deathdate_estimated` TINYINT(1) NOT NULL DEFAULT '0',
  `birthtime`           TIME                DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `person_birthdate` (`birthdate`),
  KEY `person_death_date` (`death_date`),
  KEY `person_died_because` (`cause_of_death`),
  KEY `user_who_changed_person` (`changed_by`),
  KEY `user_who_created_person` (`creator`),
  KEY `user_who_voided_person` (`voided_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `person_address` (
  `id`                INT(11)    NOT NULL AUTO_INCREMENT,
  `person_address_id` INT(11)    NOT NULL,
  `person_id`         INT(11)             DEFAULT NULL,
  `preferred`         TINYINT(1) NOT NULL DEFAULT '0',
  `address1`          VARCHAR(255)        DEFAULT NULL,
  `address2`          VARCHAR(255)        DEFAULT NULL,
  `city_village`      VARCHAR(255)        DEFAULT NULL,
  `state_province`    VARCHAR(255)        DEFAULT NULL,
  `postal_code`       VARCHAR(50)         DEFAULT NULL,
  `country`           VARCHAR(50)         DEFAULT NULL,
  `latitude`          VARCHAR(50)         DEFAULT NULL,
  `longitude`         VARCHAR(50)         DEFAULT NULL,
  `start_date`        DATETIME            DEFAULT NULL,
  `end_date`          DATETIME            DEFAULT NULL,
  `creator`           INT(11)    NOT NULL DEFAULT '0',
  `date_created`      DATETIME   NOT NULL,
  `voided`            TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`         INT(11)             DEFAULT NULL,
  `date_voided`       DATETIME            DEFAULT NULL,
  `void_reason`       VARCHAR(255)        DEFAULT NULL,
  `county_district`   VARCHAR(255)        DEFAULT NULL,
  `address3`          VARCHAR(255)        DEFAULT NULL,
  `address4`          VARCHAR(255)        DEFAULT NULL,
  `address5`          VARCHAR(255)        DEFAULT NULL,
  `address6`          VARCHAR(255)        DEFAULT NULL,
  `date_changed`      DATETIME            DEFAULT NULL,
  `changed_by`        INT(11)             DEFAULT NULL,
  `uuid`              CHAR(38)   NOT NULL,
  `facility`          CHAR(38),
  `state`             CHAR(12),
  PRIMARY KEY (`id`),
  KEY `patient_address_creator` (`creator`),
  KEY `address_for_person` (`person_id`),
  KEY `patient_address_void` (`voided_by`),
  KEY `person_address_changed_by` (`changed_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `person_attribute` (
  `id`                       INT(11)     NOT NULL AUTO_INCREMENT,
  `person_attribute_id`      INT(11)     NOT NULL,
  `person_id`                INT(11)     NOT NULL DEFAULT '0',
  `value`                    VARCHAR(50) NOT NULL DEFAULT '',
  `person_attribute_type_id` INT(11)     NOT NULL DEFAULT '0',
  `creator`                  INT(11)     NOT NULL DEFAULT '0',
  `date_created`             DATETIME    NOT NULL,
  `changed_by`               INT(11)              DEFAULT NULL,
  `date_changed`             DATETIME             DEFAULT NULL,
  `voided`                   TINYINT(1)  NOT NULL DEFAULT '0',
  `voided_by`                INT(11)              DEFAULT NULL,
  `date_voided`              DATETIME             DEFAULT NULL,
  `void_reason`              VARCHAR(255)         DEFAULT NULL,
  `uuid`                     CHAR(38)    NOT NULL,
  `facility`                 CHAR(38),
  `state`                    CHAR(12),
  PRIMARY KEY (`id`),
  KEY `attribute_changer` (`changed_by`),
  KEY `attribute_creator` (`creator`),
  KEY `defines_attribute_type` (`person_attribute_type_id`),
  KEY `identifies_person` (`person_id`),
  KEY `attribute_voider` (`voided_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `person_name` (
  `id`                 INT(11)    NOT NULL AUTO_INCREMENT,
  `person_name_id`     INT(11)    NOT NULL,
  `preferred`          TINYINT(1) NOT NULL DEFAULT '0',
  `person_id`          INT(11)    NOT NULL,
  `prefix`             VARCHAR(50)         DEFAULT NULL,
  `given_name`         VARCHAR(50)         DEFAULT NULL,
  `middle_name`        VARCHAR(50)         DEFAULT NULL,
  `family_name_prefix` VARCHAR(50)         DEFAULT NULL,
  `family_name`        VARCHAR(50)         DEFAULT NULL,
  `family_name2`       VARCHAR(50)         DEFAULT NULL,
  `family_name_suffix` VARCHAR(50)         DEFAULT NULL,
  `degree`             VARCHAR(50)         DEFAULT NULL,
  `creator`            INT(11)    NOT NULL DEFAULT '0',
  `date_created`       DATETIME   NOT NULL,
  `voided`             TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`          INT(11)             DEFAULT NULL,
  `date_voided`        DATETIME            DEFAULT NULL,
  `void_reason`        VARCHAR(255)        DEFAULT NULL,
  `changed_by`         INT(11)             DEFAULT NULL,
  `date_changed`       DATETIME            DEFAULT NULL,
  `uuid`               CHAR(38)   NOT NULL,
  `facility`           CHAR(38),
  `state`              CHAR(12),
  PRIMARY KEY (`id`),
  KEY `first_name` (`given_name`),
  KEY `last_name` (`family_name`),
  KEY `middle_name` (`middle_name`),
  KEY `family_name2` (`family_name2`),
  KEY `user_who_made_name` (`creator`),
  KEY `name_for_person` (`person_id`),
  KEY `user_who_voided_name` (`voided_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

CREATE TABLE `relationship` (
  `id`              INT(11)    NOT NULL AUTO_INCREMENT,
  `relationship_id` INT(11)    NOT NULL,
  `person_a`        INT(11)    NOT NULL,
  `relationship`    INT(11)    NOT NULL DEFAULT '0',
  `person_b`        INT(11)    NOT NULL,
  `start_date`      DATETIME            DEFAULT NULL,
  `end_date`        DATETIME            DEFAULT NULL,
  `creator`         INT(11)    NOT NULL DEFAULT '0',
  `date_created`    DATETIME   NOT NULL,
  `date_changed`    DATETIME            DEFAULT NULL,
  `changed_by`      INT(11)             DEFAULT NULL,
  `voided`          TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`       INT(11)             DEFAULT NULL,
  `date_voided`     DATETIME            DEFAULT NULL,
  `void_reason`     VARCHAR(255)        DEFAULT NULL,
  `uuid`            CHAR(38)   NOT NULL,
  `facility`        CHAR(38),
  `state`           CHAR(12),
  PRIMARY KEY (`id`),
  KEY `relation_creator` (`creator`),
  KEY `person_a_is_person` (`person_a`),
  KEY `person_b_is_person` (`person_b`),
  KEY `relationship_type_id` (`relationship`),
  KEY `relation_voider` (`voided_by`),
  KEY `relationship_changed_by` (`changed_by`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;


CREATE TABLE `visit` (
  `id`                    INT(11)    NOT NULL AUTO_INCREMENT,
  `visit_id`              INT(11)    NOT NULL,
  `patient_id`            INT(11)    NOT NULL,
  `visit_type_id`         INT(11)    NOT NULL,
  `date_started`          DATETIME   NOT NULL,
  `date_stopped`          DATETIME            DEFAULT NULL,
  `indication_concept_id` INT(11)             DEFAULT NULL,
  `location_id`           INT(11)             DEFAULT NULL,
  `creator`               INT(11)    NOT NULL,
  `date_created`          DATETIME   NOT NULL,
  `changed_by`            INT(11)             DEFAULT NULL,
  `date_changed`          DATETIME            DEFAULT NULL,
  `voided`                TINYINT(1) NOT NULL DEFAULT '0',
  `voided_by`             INT(11)             DEFAULT NULL,
  `date_voided`           DATETIME            DEFAULT NULL,
  `void_reason`           VARCHAR(255)        DEFAULT NULL,
  `uuid`                  CHAR(38)   NOT NULL,
  `facility`              CHAR(38),
  `state`                 CHAR(12),
  PRIMARY KEY (`id`),
  KEY `visit_patient_index` (`patient_id`),
  KEY `visit_type_fk` (`visit_type_id`),
  KEY `visit_location_fk` (`location_id`),
  KEY `visit_creator_fk` (`creator`),
  KEY `visit_voided_by_fk` (`voided_by`),
  KEY `visit_changed_by_fk` (`changed_by`),
  KEY `visit_indication_concept_fk` (`indication_concept_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8